import "@/app/css/globals.css";
import { Toaster } from "@/components/ui/sonner";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";

import { Navbar } from "./components/Navbar";
import ThemeProvider from "./components/theme-provider";

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "600", "800"] });

export const metadata: Metadata = {
  title: "Tailwind play",
  description: "Generated by create next app",
};
export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider>
          <>
            <Navbar />
            {children}
            <Toaster />
          </>
        </ThemeProvider>
      </body>
    </html>
  );
}
