import "@/app/css/globals.css";
import { Toaster } from "@/components/ui/sonner";
import type { Metadata } from "next";

import { Navbar } from "./components/Navbar";
import ThemeProvider from "./components/theme-provider";
import { Redux } from "./redux/Redux";


export const metadata: Metadata = {
  title: "Tailwind play",
  description: "Generated by create next app",
  authors: { name: "Moinak Majumdar", url: 'https://moinak05.vercel.app' }
};


export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider>
          <Redux>
            <Navbar />
            {children}
            <Toaster />
          </Redux>
        </ThemeProvider>
      </body>
    </html>
  );
}
